version: "3.8"
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:80"
    environment:
      PUBLIC_KEY: asdfasdf
